@startuml
skinparam package {
  BorderColor transparent
  BackgroundColor transparent
  Shadowing false
}
skinparam rectangle {
  BorderColor black
  BackgroundColor lightgrey
  Shadowing false
  FontStyle normal
}
skinparam agent {
  BorderColor lightgrey
  BackgroundColor lightgrey
  FontColor lightgrey
  Shadowing false
}

hide footbox
'skinparam svgDimensionStyle false
skinparam linetype polyline
package "  "  {
  rectangle "[[#beneficiary-requestor Beneficiary        \nRequestor]]" as br {
    agent "Benefits" as BenReq
  }
  rectangle "[[#coverage-requestor Coverage        \nRequestor]]" as cr {
    agent "Coverage" as CovReq
  }
  rectangle "[[#claims-requestor Claims               \nRequestor]]" as cl {
    agent "Claims" as ClaimReq
  }
}

package " "  {
  rectangle "[[#beneficiary-manager Beneficiary\nManager]]" as Ben {
    agent "Benefits" as BenMan
  }
  rectangle "[[#claims-manager Claims            \nManager]]" as ClaimMan {
    agent "Claims" as ClaimMan1
    agent "Claims" as ClaimMan2
  }
}
BenReq -> BenMan : "[[ITI-121.html Query Insurance Plan &#91;ITI-121&#93;]]"
BenReq -> BenMan : "[[ITI-122.html Enroll Beneficiary &#91;ITI-122&#93;]]"
BenReq -> BenMan : "[[ITI-123.html Check Enrollment Status &#91;ITI-123&#93;]]"
BenReq -[hidden]-> CovReq: ""
CovReq -[hidden]-> ClaimReq: ""
BenMan -[hidden]-> ClaimMan1: ""
ClaimMan1 -[hidden]-> ClaimMan2: ""
CovReq -> ClaimMan1 : "[[ITI-124.html Check Coverage Eligibility &#91;ITI-124&#93;]]"
CovReq -> ClaimMan1 : "[[ITI-125.html Check Coverage Eligibility Status &#91;ITI-125&#93;]]"
ClaimReq -> ClaimMan2 : "[[ITI-YY5.html Submit Claim &#91;ITI-YY5&#93;]]"
ClaimReq -> ClaimMan2 : "[[ITI-YY8.html Cancel Claim &#91;ITI-YY8&#93;]]"
ClaimReq -> ClaimMan2 : "[[ITI-YY9.html Re-process Claim &#91;ITI-YY9&#93;]]"
ClaimReq -> ClaimMan2 : "[[ITI-YY6.html Track Claim &#91;ITI-YY6&#93;]]"


@endum
