@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"
participant "Beneficiary Requestor" as Req
participant "Claims Manager" as Man
activate Req
activate Man
Req -> Man : Check Coverage Eligibility Request:\nHTTP POST <Base>/CoverageEligibilityRequest/$submit
Man --> Req : Check Coverage Eligibility Response:\nCoverageEligibilityResponse or Bundle
deactivate Man
deactivate Req
@enduml
