@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"
participant "Beneficiary Requestor" as Req
participant "Beneficiary Manager" as Man
activate Req
activate Man
Req -> Man : Search Enrollment Response Request:\nHTTP GET <Base>/EnrollmentResponse [ITI-YY2]
Man --> Req : Search Enrollment Response Response:\nBundle
deactivate Man
deactivate Req

Req -[hidden]> Man
activate Req
activate Man 
Req -> Man : Read Enrollment Response Request:\nHTTP GET <Base>/EnrollmentResponse/<ResourceId> [ITI-YY2]
Man --> Req : Read Enrollment Response Response:\nEnrollmentResponse
deactivate Man
deactivate Req

@enduml
