@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"
participant "Claims Requestor" as Req
participant "Claims Manager" as Man
activate Req
activate Man
Req -> Man : Re-Process Claim Request:\nHTTP POST <Base>/Claim/<ResourceId>$reprocess
Man --> Req : Re-Process Claim Response:\nClaim Response or Bundle
deactivate Man
deactivate Req
@enduml
