@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"
participant "Beneficiary Requestor" as Req
participant "Beneficiary Manager" as Man
activate Req
activate Man
Req -> Man : Search Insurance Plan Request:\nHTTP GET <Base>/InsurancePlan?<Parameters>
Man --> Req : Search Insurance Plan Response:\nBundle
deactivate Man
deactivate Req

Req -[hidden]> Man
activate Req
activate Man 
Req -> Man : Read Insurance Plan Request:\nHTTP GET <Base>/InsurancePlan/<ResourceId>
Man --> Req : Read Insurance Plan Response:\nInsurancePlan
deactivate Man
deactivate Req

@enduml
