@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"
participant "Beneficiary Requestor" as Req
participant "Beneficiary Manager" as Man
activate Req
activate Man
Req -> Man : Enroll Beneficiary Request:\nHTTP POST <Base>/EnrollmentRequest/$submit
Man --> Req : Enroll Beneficiary Response:\nEnrollmentResponse or Bundle
deactivate Man
deactivate Req
@enduml
