@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant "Beneficiary Requestor" as BR 
participant "Beneficiary Manager" as BM 

participant "Coverage Requestor" as CV

participant "Claims Requestor" as CR 
participant "Claims Manager" as CM 


group Enroll Beneficiary
  activate BR
  activate BM
  BR->BM: Query Insurance Plans (InsurancePlan)\nITI-121
  BM->BR: Return Matching Insurance Plans\nITI-121
  BR->BM: Enroll Beneficiary (EnrollmentRequest/$submit)\nITI-122
  alt Success
    BM->BR: Return Enrolled Response (EnrollmentResponse)\nITI-122
  else Queued
    BM->BR: Return Queued Response (EnrollmentResponse)\nITI-122
    loop Check Enrollment Status 
      BR->BM: Check Enrollment Status (EnrollmentResponse/ID)\nITI-123
      BM->BR: Return Enrolled Response (EnrollmentResponse)\nITI-123
      note right: Continue with workflow if completed or continue loop
    end
  else Error
    BM->BR: Return Error (OperationOutcome)\nITI-122
  end
  deactivate BM
  deactivate BR
end

group Patient Visit
  activate CM
  activate CV
  CV->CM: Check Patient's Coverage (CoverageEligibilityRequest/$submit)\nITI-YY4
  alt Success (covered or not)
    CM->CV: Return Eligibility (CoverageEligibilityResponse)\nITI-YY4
  else Queued 
    CM->CV: Return Queued Response (CoverageEligibilityResponse)\nITI-YY4
    loop Check Eligibility Status
      CV->CM: Check Eligibility Status (CoverageEligibilityResponse)\nITI-YY7
      CM->CV: Return Eligibility Response (CoverageEligibilityResponse)\nITI-YY7
      note right: Continue with workflow if completed or continue loop.
    end
  else Error
    BM->BR: Return Error (OperationOutcome)\nITI-YY4
  end
  deactivate CV

  activate CR
  opt Pre-Determination 
    CR->CM: Submit pre-determination (Claim/$submit use=predetermination)\nITI-YY5
    alt Success (accept or denied)
      CM->CR: Return Pre-determination Response (ClaimResponse)\nITI-YY5
    else Queued 
      CM->CR: Return Queued Response (ClaimResponse)\nITI-YY5
      alt Check Pre-determination Status
        loop Check Pre-determination Status
          CR->CM: Check Pre-determination Status (ClaimResponse)\nITI-YY6
          CM->CR: Return Pre-determination Response (ClaimResponse)\nITI-YY6
          note right: Continue with workflow if completed or continue loop.
        end
      else Cancel Claim
        CR->CR: Process cancel claim option
      end
    else Error
      CM->CR: Return Error (OperationOutcome)\nITI-YY5
    end
  end

  opt Pre-Authorization
    CR->CM: Submit pre-authorization (Claim/$submit use=preauthorization)\nITI-YY5
    alt Success (accept or denied)
      CM->CR: Return Pre-authorization Response (ClaimResponse)\nITI-YY5
    else Queued 
      CM->CR: Return Queued Response (ClaimResponse)\nITI-YY5
      alt Check Pre-authorization Status
        loop Check Pre-authorization Status
          CR->CM: Check Pre-authorization Status (ClaimResponse)\nITI-YY6
          CM->CR: Return Pre-authorization Response (ClaimResponse)\nITI-YY6
          note right: Continue with workflow if completed or continue loop.
        end
      else Cancel Claim
        CR->CR: Process cancel claim option
      end
    else Error
      CM->CR: Return Error (OperationOutcome)\nITI-YY5
    end
  end

  opt File Claim
    CR->CM: Submit Claim (Claim/$submit use=claim)\nITI-YY5
    alt Covered
      CM->CR: Return Claim Response (ClaimResponse)\nITI-YY5
    else Denied
      opt Re-process Claim
        CR->CM: Re-process Claim (Claim/ID/$reprocess)\nITI-YY9
        alt Success
          CM->CR: Return Claim Response (ClaimResponse)\nITI-YY9
        else Queued 
          CM->CR: Return Queued Response (ClaimResponse)\nITI-YY9
          alt Check Claim Status
            loop Check Claim Status
              CR->CM: Check Claim Status (ClaimResponse)\nITI-YY6
              CM->CR: Return Claim Response (ClaimResponse)\nITI-YY6
              note right: Continue with workflow if completed or continue loop.
            end
          else Cancel Claim
            CR->CR: Process cancel claim option
          end
        else Error
          CM->CR: Return Error (OperationOutcome)\nITI-YY9
        end
      end
    else Queued 
      CM->CR: Return Queued Response (ClaimResponse)\nITI-YY5
      loop Check Claim Status
        CR->CM: Check Claim Status (ClaimResponse)\nITI-YY6
        CM->CR: Return Claim Response (ClaimResponse)\nITI-YY6
        note right: Continue with workflow if completed or continue loop.
      end
    else Error
      CM->CR: Return Error (OperationOutcome)\nITI-YY5
    end

  end

  opt Cancel Claim
    CR->CM: Submit Claim (Claim/ID/$cancel)\nITI-YY8
    alt Success
      CM->CR: Return Claim Response (ClaimResponse)\nITI-YY8
    else Queued 
      CM->CR: Return Queued Response (ClaimResponse)\nITI-YY8
      loop Check Claim Status
        CR->CM: Check Claim Status (ClaimResponse)\nITI-YY6
        CM->CR: Return Claim Response (ClaimResponse)\nITI-YY6
        note right: Continue with workflow if completed or continue loop.
      end
    else Error
      CM->CR: Return Error (OperationOutcome)\nITI-YY8
    end
  end

  deactivate CR
  deactivate CM

end

@enduml
