@startuml

title Enroll Beneficiary Workflow

start
:collect beneficiary data;
:query insurance plans\nQuery Insurance Plan &#91;ITI-YY2&#93;<
:build enrollment request|
:submit enrollment request\nEnroll Beneficiary &#91;ITI-YY1&#93;>
while (process results ?) is (queued)
  :query response updates\nCheck Enrollment Status &#91;ITI-YY3&#93;<
endwhile (completed)
:process enrollment response|
stop

@enduml
