@startuml

title Enroll Beneficiary Workflow

start
:enroll beneficiary;
:query insurance plans\nITI-YY2;
:build enrollment request;
:submit enrollment request\nITI-YY1;
while (process results ?) is (queued)
  :query response updates\nITI-YY3;
endwhile (completed)
:process enrollment response;
stop

@enduml
