@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS


opt Get code lists for Medical Procedures & Items
	PoS -> FIS: Submit Medical Procedures & Items Query
	FIS -> FIS: Process query
	FIS -> PoS: Return  Medical Procedures & Items
end opt
 

PoS -> FIS: Submit Coverage Eligibility Query
FIS -> FIS: Process Insuree Query
FIS -> FIS: Process Policy Query
FIS -> PoS: Return Coverage Eligibility Result

@enduml
