@startuml
skinparam svgDimensionStyle false
hide footbox

participant "PoS\nClaims Requestor" as App
participant "FIS\nClaims Manager" as FIS
participant "External Payment System" as EXT


opt Get code lists for Medical Procedures & Items
	App -> App: Lookup Medical Procedures & Items codes
	App -> FIS: Verify codes
	FIS -> App: Confirm codes
end opt
 
App -> App: Build claim
App -> FIS: Submit claim\n&#91;ITI-126&#93; Submit Claim request
FIS -> FIS: Process claim

alt accepted
	opt Payout
		FIS->EXT: Send payment request
   	EXT->EXT: Process payment
	end opt
	FIS -> App: Return positive claim result\n&#91;ITI-126&#93; Submit Claim response
else rejected
	FIS -> App: Return negative claim result\n&#91;ITI-126&#93; Submit Claim response
	opt Re-process claim
		App -> FIS: Re-submit claim for re-processing\n&#91;ITI-YY9&#93; Re-process Claim request
		Fis -> App: Return claim re-process response\n&#91;ITI-YY9&#93; Re-processUpdate Claim response
	end opt
else queued
	FIS -> App: Return queued status notification\n&#91;ITI-126&#93; Submit Claim response
	opt Cancel claim
		App -> FIS: Cancel claim\n&#91;ITI-127&#93; Cancel Claim request
		Fis -> App: Return claim cancellation response\n&#91;ITI-127&#93; Cancel Claim response
	end opt
end

@enduml
