@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS


opt Get code lists for medical procedures & items
	PoS -> FIS: Submit medical procedures & items query
	FIS -> FIS: Process query
	FIS -> PoS: Return  medical procedures & items
end opt
 

PoS -> PoS: Build pre-authorization
PoS -> FIS: Submit pre-authorization
FIS -> FIS: Process pre-authorization

alt accepted
	FIS -> PoS: Return positive pre-authorization result
else rejected
	FIS -> PoS: Return negative pre-authorization result
else queued
	FIS -> PoS: Return queued status notification
end

@enduml
