@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS
participant EXT


opt Get code lists for medical procedures & items
	PoS -> FIS: Submit medical procedures & items query
	FIS -> FIS: Process query
	FIS -> PoS: Return  medical procedures & items
end opt
 

PoS -> PoS: Build claim
PoS -> FIS: Submit claim (use)
FIS -> FIS: Process claim

alt accepted
	opt Payout
    	note over IOL, EXT: Process payment
	end opt
	FIS -> PoS: Return positive claim result
else rejected
	FIS -> PoS: Return negative claim result
else queued
	FIS -> PoS: Return queued status notification
end

@enduml
