@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant "App\nBeneficiary Requestor\nnPatient Demographics Consumer" as App
participant "FIS\nBeneficiary Manager" as FIS
participant "Client Registry\nPatient Identity Registry" as CR


opt
  App->CR: Request demograhpics data\nITI-78 Mobile Patient Demographics Query request
  CR->App: Return demographics details\nITI-78 Mobile Patient Demographics Query response
end

App->FIS: Submit Patient/Beneficiary Query (Demographics / ID)\nITI-YY2 Query Beneficiary request
FIS->FIS: Process query
FIS->App: Return Beneficiary Details response\nITI-YY2 Query Beneficiary response

@enduml
