@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS


opt Get code lists for medical procedures & items
	PoS -> FIS: Submit medical procedures & items query
	FIS -> FIS: Process query
	FIS -> PoS: Return  medical procedures & items
end opt
 

PoS -> PoS: Build pre-determination
PoS -> FIS: Submit pre-determination
FIS -> FIS: Process pre-determiniation

alt accepted
	FIS -> PoS: Return positive pre-determiniation result
else rejected
	FIS -> PoS: Return negative pre-determiniation result
else queued
	FIS -> PoS: Return queued status notification
end

@enduml
