@startuml
skinparam svgDimensionStyle false
hide footbox

participant "PoS\nCoverage Requestor" as App
participant "FIS\nClaims Manager" as FIS


opt Get code lists for Medical Procedures & Items
	App -> App: Lookup Medical Procedures & Items codes
	App -> FIS: Verify codes
	FIS -> App: Confirm codes
end opt

App -> FIS: Submit Coverage Eligibility Query\n&#91;ITI-YY4&#93; Check Coverage Eligibility request
FIS -> FIS: Process Insuree Query
FIS -> FIS: Process Policy Query
FIS -> App: Return Coverage Eligibility Result\n&#91;ITI-YY4&#93; Check Coverage Eligibility response

@enduml
