@startuml
skinparam svgDimensionStyle false
hide footbox

participant POS
participant FIS

POS -> FIS: Submit claim response query (Claim ID)\n&#91;ITI-129&#93; Track Claim request
FIS -> FIS: Process query

alt approved
	FIS -> POS: Return approved claim response\n&#91;ITI-129&#93; Track Claim response
else denied
	FIS -> POS: Return denied claim response\n&#91;ITI-129&#93; Track Claim response
else queued
	FIS -> POS: Return queued claim response\n&#91;ITI-129&#93; Track Claim response
else not found
	FIS -> POS: Return not found notification\n&#91;ITI-129&#93; Track Claim response
end

@enduml
