@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant IOL
participant FIS
participant EXT


opt Get code lists for medical procedures & items
	PoS -> IOL: Submit medical procedures & items query
	IOL -> FIS: Forward query
	FIS -> FIS: Process query
	FIS -> IOL: Return  medical procedures & items
	IOL -> PoS: Forward medical procedures & items
end opt
 

PoS -> PoS: Build pre-determination
PoS -> IOL: Submit pre-determination
IOL -> FIS: Forward pre-determination
FIS -> FIS: Process pre-determiniation

alt accepted
	FIS -> IOL: Return positive pre-determiniation result
	IOL -> PoS: Forward positive pre-determiniation result
else rejected
	FIS -> IOL: Return negative pre-determiniation result
	IOL -> PoS: Forward negative pre-determiniation result
else queued
	FIS -> IOL: Return queued status notification
	IOL -> PoS: Forward queued status notification
end

@enduml
