@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant IOL
participant FIS


PoS->IOL: Submit Patient/Beneficiary Query (Demographics / ID)
IOL->FIS: Forward Query details

FIS->FIS: Process query

FIS->IOL: Return Beneficiary Details response

IOL->PoS: Forward Beneficiary Details response

@enduml
