@startuml
skinparam svgDimensionStyle false
hide footbox

participant POS
participant FIS


opt Get code lists for medical procedures & items
	POS -> FIS: Submit medical procedures & items query
	FIS -> FIS: Process query
	FIS -> POS: Return  medical procedures & items
end opt
 

POS -> POS: Build pre-determination
POS -> FIS: Submit pre-determination\n&#91;ITI-126&#93; Submit Claim request
FIS -> FIS: Process pre-determiniation

alt accepted
	FIS -> POS: Return positive pre-determination result\n&#91;ITI-126&#93; Submit Claim response
else rejected
	FIS -> POS: Return negative pre-determination result\n&#91;ITI-126&#93; Submit Claim response
else queued
	FIS -> POS: Return queued status notification\n&#91;ITI-126&#93; Submit Claim response
end

@enduml
