@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS

PoS -> FIS: Submit claim response query (Claim ID)\nITI-YY6 Track Claim request
FIS -> FIS: Process query

alt accepted
	FIS -> PoS: Return positive claim result\nITI-YY6 Track Claim response
else rejected
	FIS -> PoS: Return negative claim result\nITI-YY6 Track Claim response
else queued
	FIS -> PoS: Return queued status notification\nITI-YY6 Track Claim response
else not found
	FIS -> PoS: Return not found notification\nITI-YY6 Track Claim response
end

@enduml
