@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS


opt Get code lists for medical procedures & items
	PoS -> FIS: Submit medical procedures & items query
	FIS -> FIS: Process query
	FIS -> PoS: Return  medical procedures & items
end opt
 

PoS -> PoS: Build pre-authorization
PoS -> FIS: Submit pre-authorization\nITI-YY4 Submit Claim request
FIS -> FIS: Process pre-authorization

alt accepted
	FIS -> PoS: Return positive pre-authorization result\nITI-YY5 Submit Claim response
else rejected
	FIS -> PoS: Return negative pre-authorization result\nITI-YY5 Submit Claim response
else queued
	FIS -> PoS: Return queued status notification\nITI-YY5 Submit Claim response
end

@enduml
