@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant "PoS\nBeneficiary Requestor" as App
participant "FIS\nBeneficiary Manager" as FIS


opt Get code lists for Medical Procedures & Items
	App -> App: Lookup Medical Procedures & Items codes
	App -> FIS: Verify codes
	FIS -> App: Confirm codes
end opt

App -> FIS: Submit Coverage Eligibility Query
FIS -> FIS: Process Insuree Query
FIS -> FIS: Process Policy Query
FIS -> App: Return Coverage Eligibility Result

@enduml
