@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS

PoS -> FIS: Submit claim response query (Claim ID)
FIS -> FIS: Process query

alt accepted
	FIS -> PoS: Return positive claim result
else rejected
	FIS -> PoS: Return negative claim result
else queued
	FIS -> PoS: Return queued status notification
else not found
	FIS -> PoS: Return not found notification
end

@enduml
