@startuml
skinparam svgDimensionStyle false
hide footbox
autonumber "<b>[0]"

participant PoS
participant FIS

PoS->FIS: Submit enrollment request
FIS->FIS: Verify enrollment eligibility

alt success
  FIS->FIS: Process enrollment
  FIS->PoS: Return positive enrollment response
  PoS->PoS: Add details to patient record
else validation error
  FIS->PoS: Return negative enrollment response
end

@enduml
