# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.fais
canonical: https://profiles.ihe.net/ITI/FAIS
version: 1.0.0-current
name: IHE_ITI_FAIS
title: "Finance and Insurance Service (FAIS)"
description: The Finance and Insurance Service (FAIS) stores, categorizes, and facilitates the administration of centralized claims and finance data for patient care. The service receives claims/financial data from Point of Service applications (including financing applications acting as a point of service interface outside of other PoS systems) and curates the management of them.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2024-08-09
status: active
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+
dependencies:
  ihe.iti.balp: 1.1.x # current # 1.1.1

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  path-binary:
    - input/tests
  path-pages:
    - input/tests

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: Finance and Insurance Service (FAIS) Home
    generation: markdown
  volume-1.md:
    title: 1:XX Finance and Insurance Service (FAIS)
    generation: markdown
  ITI-121.md:
    title: 2:3.121 Query Insurance Plan [ITI-121]
    generation: markdown
  ITI-122.md:
    title: 2:3.122 Enroll Beneficiary [ITI-122]
    generation: markdown
  ITI-123.md:
    title: 2:3.123 Check Enrollment Status [ITI-123]
    generation: markdown
  ITI-124.md:
    title: 2:3.124 Check Coverage Eligibility [ITI-124]
    generation: markdown
  ITI-125.md:
    title: 2:3.125 Check Coverage Eligibility Status [ITI-125]
    generation: markdown
  ITI-126.md:
    title: 2:3.126 Submit Claim [ITI-126]
    generation: markdown
  ITI-127.md:
    title: 2:3.127 Cancel Claim [ITI-127]
    generation: markdown
  ITI-128.md:
    title: 2:3.128 Re-process Claim [ITI-128]
    generation: markdown
  ITI-129.md:
    title: 2:3.129 Track Claim [ITI-129]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  FAIS Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    "Query Insurance Plan [ITI-121]": ITI-121.html
    "Enroll Beneficiary [ITI-122]": ITI-122.html
    "Check Enrollment Status [ITI-123]": ITI-123.html
    "Check Coverage Eligibility [ITI-124]": ITI-124.html
    "Check Coverage Eligibility Status [ITI-125]": ITI-125.html
    "Submit Claim [ITI-126]": ITI-126.html
    "Cancel Claim [ITI-127]": ITI-127.html
    "Re-process Claim [ITI-128]": ITI-128.html
    "Track Claim [ITI-129]": ITI-129.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
